from __future__ import annotations


NON_BRAND_CLASSES = {
    "no_brand",
    "unknown_logo",
}


KNOWN_BRAND_CLASSES = {
    "nike",
    "adidas",
    "jordan",
    "gucci",
    "louis_vuitton",
    "puma",
    "reebok",
    "under_armour",
    "off_white",
    "supreme",
    "chanel",
    "dior",
    "calvin_klein",
    "stussy",
    "thrasher",
    "balenciaga",
    "prada",
    "versace",
    "new_balance",
    "fila",
}


OCR_BRAND_KEYWORDS = {
    "nike",
    "adidas",
    "air jordan",
    "jordan",
    "puma",
    "reebok",
    "new balance",
    "under armour",
    "fila",
    "asics",
    "vans",
    "converse",
    "champion",
    "umbro",
    "kappa",
    "ellesse",
    "diadora",
    "lotto",
    "mizuno",
    "salomon",
    "hoka",
    "skechers",

    "the north face",
    "tnf",
    "columbia",
    "patagonia",
    "napapijri",
    "helly hansen",
    "carhartt",
    "carhartt wip",
    "timberland",
    "dr martens",
    "doc martens",
    "crocs",

    "supreme",
    "stussy",
    "thrasher",
    "palace",
    "obey",
    "huf",
    "ripndip",
    "anti social social club",
    "assc",
    "a bathing ape",
    "bape",
    "fear of god",
    "essentials",
    "fog essentials",
    "vlone",
    "off-white",
    "off white",
    "heron preston",
    "nocta",
    "corteiz",
    "crtz",
    "trapstar",
    "represent",
    "sp5der",
    "rhude",

    "gucci",
    "prada",
    "balenciaga",
    "louis vuitton",
    "lv",
    "chanel",
    "dior",
    "versace",
    "fendi",
    "burberry",
    "hermes",
    "saint laurent",
    "ysl",
    "yves saint laurent",
    "givenchy",
    "valentino",
    "armani",
    "giorgio armani",
    "emporio armani",
    "dolce gabbana",
    "dolce & gabbana",
    "d&g",
    "bottega veneta",
    "celine",
    "loewe",
    "balmain",
    "kenzo",
    "maison margiela",
    "margiela",
    "moschino",
    "alexander mcqueen",
    "vivienne westwood",
    "rick owens",
    "raf simons",
    "yohji yamamoto",
    "comme des garcons",
    "cdg",
    "issey miyake",
    "jacquemus",
    "moncler",
    "stone island",
    "cp company",
    "c.p. company",
    "palm angels",
    "amiri",
    "dsquared2",

    "zara",
    "bershka",
    "pull bear",
    "pull&bear",
    "h&m",
    "hm",
    "uniqlo",
    "mango",
    "reserved",
    "cropp",
    "house",
    "sinsay",
    "stradivarius",
    "massimo dutti",
    "gap",
    "old navy",
    "banana republic",
    "tommy hilfiger",
    "calvin klein",
    "ck",
    "guess",
    "diesel",
    "levis",
    "levi's",
    "lee",
    "wrangler",
    "g-star",
    "g star",
    "lacoste",
    "fred perry",
    "ralph lauren",
    "polo ralph lauren",
    "hugo boss",
    "boss",
    "gant",
    "superdry",
    "jack jones",
    "jack & jones",

    "arc'teryx",
    "arcteryx",
    "mammut",
    "marmot",
    "black diamond",
    "jack wolfskin",
    "fjallraven",
    "fjällräven",
    "oakley",
    "quiksilver",
    "roxy",
    "billabong",
    "volcom",
    "dc shoes",
    "element",
    "hurley",
    "o'neill",
    "oneill",

    "playboy",
    "nasa",
    "hard rock",
    "harley davidson",
    "harley-davidson",
}