from __future__ import annotations


APPAREL_CONFIDENCE_THRESHOLD = 0.88
NON_APPAREL_BLOCK_CONFIDENCE = 0.95

QUALITY_MIN_WIDTH = 256
QUALITY_MIN_HEIGHT = 256
QUALITY_MIN_LAPLACIAN_VARIANCE = 40.0
QUALITY_CRITICAL_SCORE = 0.35

SAFE_MARGIN_RATIO = 0.03

TOO_MUCH_TEXT_WORDS = 50
TOO_MUCH_TEXT_BLOCKS = 20

SKEW_DOCUMENT_ANGLE_DEG = 8.0
SKEW_APPAREL_ANGLE_DEG = 18.0
SKEW_DOCUMENT_SUPPORT_LINES = 5
SKEW_APPAREL_SUPPORT_LINES = 12
SKEW_DOCUMENT_CONFIDENCE = 0.45
SKEW_APPAREL_CONFIDENCE = 0.75

MESSY_LINES_COUNT = 80
APPAREL_MESSY_LINES_COUNT = 350

LOGO_LIKE_REVIEW_COUNT = 8
APPAREL_LOGO_LIKE_REVIEW_COUNT = 20
VISUAL_LOGO_CENTER_SCORE = 0.88
VISUAL_LOGO_CENTER_AREA_RATIO = 0.08
VISUAL_LOGO_CENTER_DISTANCE = 0.20
VISUAL_LOGO_MEDIUM_SCORE = 0.82
VISUAL_LOGO_MEDIUM_AREA_RATIO = 0.04

WATERMARK_WEAK_SCORE = 0.82
WATERMARK_STRONG_SCORE = 0.90
WATERMARK_BLOCK_SCORE = 0.96
WATERMARK_STRONG_AREA_RATIO = 0.015
WATERMARK_CENTEREDNESS = 0.35