from __future__ import annotations


APPAREL_CONFIDENCE_THRESHOLD = 0.65
NON_APPAREL_BLOCK_CONFIDENCE = 0.88

QUALITY_MIN_WIDTH = 256
QUALITY_MIN_HEIGHT = 256
QUALITY_MIN_LAPLACIAN_VARIANCE = 40.0
QUALITY_CRITICAL_SCORE = 0.35

SAFE_MARGIN_RATIO = 0.05
TOO_MUCH_TEXT_WORDS = 12
TOO_MUCH_TEXT_BLOCKS = 5

SKEW_DOCUMENT_ANGLE_DEG = 8.0
SKEW_APPAREL_ANGLE_DEG = 12.0
SKEW_DOCUMENT_SUPPORT_LINES = 5
SKEW_APPAREL_SUPPORT_LINES = 8
SKEW_DOCUMENT_CONFIDENCE = 0.45
SKEW_APPAREL_CONFIDENCE = 0.60

MESSY_LINES_COUNT = 45
APPAREL_MESSY_LINES_COUNT = 65

LOGO_LIKE_REVIEW_COUNT = 3
APPAREL_LOGO_LIKE_REVIEW_COUNT = 5
VISUAL_LOGO_CENTER_SCORE = 0.68
VISUAL_LOGO_CENTER_AREA_RATIO = 0.02
VISUAL_LOGO_CENTER_DISTANCE = 0.38
VISUAL_LOGO_MEDIUM_SCORE = 0.62
VISUAL_LOGO_MEDIUM_AREA_RATIO = 0.008

WATERMARK_WEAK_SCORE = 0.78
WATERMARK_STRONG_SCORE = 0.88
WATERMARK_BLOCK_SCORE = 0.94
WATERMARK_STRONG_AREA_RATIO = 0.01
WATERMARK_CENTEREDNESS = 0.45
